environment:
  EXAMPLES: calculator console membership turbo_blank
  VERBOSE: true
  matrix:
    # 32-bit
    - RUBY_VERSION: 23
      RUST_HOST: i686-pc-windows-msvc
      RUST_VERSION: stable


install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-toolchain=%RUST_VERSION% --default-host=%RUST_HOST%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;%APPVEYOR_BUILD_FOLDER%\ruby\windows_build;%PATH%
  - echo %PATH%
  - set HELIX_ROOT=%APPVEYOR_BUILD_FOLDER%
  - bash ./scripts/ci-install

test_script:
  - rake

build: off

#init:
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
