environment:
  EXAMPLES: console
  VERBOSE: true
  matrix:
    # 32-bit
    - RUBY_VERSION: 21
      RUST_HOST: i686-pc-windows-msvc
      RUST_VERSION: stable

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-toolchain=%RUST_VERSION% --default-host=%RUST_HOST%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86

test_script:
  - cl.exe c/lib.c /Foruby.obj /c
  - link.exe ruby.obj /dll /out:ruby.dll
  - cl.exe c/foo.c ruby.lib /Femyruby.exe
  - rustc.exe c/lib.rs --crate-type cdylib -L. --crate-name rust
  - .\myruby.exe

  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby bar.rb
  - rustc lib.rs --crate-type cdylib -L.
  - copy lib.dll native.so
  - ruby foo.rb

build: off
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
